make changes

diff --git a/Dockerfile.prod b/Dockerfile.prod
--- a/Dockerfile.prod
+++ b/Dockerfile.prod
@@ -1,19 +1,57 @@
-# Build stage
-FROM node:22-alpine AS build
+FROM node:22-alpine AS base
 
-WORKDIR /src
-COPY package.json .
-RUN npm install
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
+
+# Install dependencies
+COPY package.json yarn.lock* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 
-RUN npm run build
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+ENV NEXT_TELEMETRY_DISABLED=1
 
-# Production stage
-FROM build AS production
+RUN \
+  if [ -f yarn.lock ]; then yarn build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-COPY --from=build /src/.next ./.next
-COPY --from=build /src/node_modules ./node_modules
-COPY --from=build /src/package.json ./package.json
-COPY --from=build /src/public ./public
+# Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
 
-CMD npm start
+ENV NODE_ENV=production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+ENV NEXT_TELEMETRY_DISABLED=1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
+ENV PORT=5918
+
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/next-config-js/output
+ENV HOSTNAME="0.0.0.0"
+CMD ["node", "server.js"]
